/** Curated “Can Morris take…?” item directory — honest acceptance guidance. */

export type ItemAcceptance = "usually" | "sometimes" | "special" | "rarely" | "no";

export type AuthorityItem = {
  slug: string;
  name: string;
  title: string;
  description: string;
  keywords: string[];
  acceptance: ItemAcceptance;
  canRemove: string;
  specialHandling: string;
  recycling: string;
  donation: string;
  manualReview: string;
  pricingFactors: string[];
  relatedServices: string[];
  relatedGuides: string[];
  relatedItems: string[];
  faqs: Array<{ q: string; a: string }>;
};

export const AUTHORITY_ITEMS: AuthorityItem[] = [
  {
    slug: "couch-sofa",
    name: "Couch / Sofa",
    title: "Couch & Sofa Removal | Morris Junk Removal",
    description:
      "Couch and sofa removal in Warren County and nearby Missouri — photo estimates, stairs notes, and donation when condition allows.",
    keywords: ["couch removal", "sofa removal Missouri", "sectional removal"],
    acceptance: "usually",
    canRemove: "Yes — couches, sectionals, loveseats, and most upholstered sofas.",
    specialHandling: "Sectionals and sleeper sofas may need extra labor. Note stairs and doorway width.",
    recycling: "Metal frames may be recoverable; foam and fabric usually are not recycled locally.",
    donation: "Clean, usable sofas may be donation candidates. Stained, torn, or pest-exposed pieces usually cannot be donated.",
    manualReview: "Rare for standard sofas. Oversized sectionals upstairs may need review.",
    pricingFactors: ["Size", "Stairs / long carry", "Whether disassembled", "Condition notes"],
    relatedServices: ["furniture-removal", "mattress-removal"],
    relatedGuides: ["donation-vs-disposal", "how-junk-removal-pricing-works"],
    relatedItems: ["recliner", "mattress-box-spring", "office-furniture"],
    faqs: [
      {
        q: "Do you remove a single couch?",
        a: "Yes. Single-item pickups are common. Travel and labor still apply.",
      },
    ],
  },
  {
    slug: "recliner",
    name: "Recliner",
    title: "Recliner Removal | Morris Junk Removal",
    description: "Recliner removal with photo estimates for Warren County and nearby Missouri homes.",
    keywords: ["recliner removal", "chair junk removal"],
    acceptance: "usually",
    canRemove: "Yes — standard and oversized recliners.",
    specialHandling: "Power recliners: unplug and note if mechanisms are stuck.",
    recycling: "Limited — metal components may be recoverable.",
    donation: "Possible if clean and working. Broken recliners usually go to disposal.",
    manualReview: "Uncommon.",
    pricingFactors: ["Weight", "Stairs", "Power vs manual"],
    relatedServices: ["furniture-removal"],
    relatedGuides: ["prepare-for-junk-removal"],
    relatedItems: ["couch-sofa", "office-furniture"],
    faqs: [{ q: "Can you take a stuck recliner?", a: "Usually yes. Tell us if it will not fold — carry path matters." }],
  },
  {
    slug: "mattress-box-spring",
    name: "Mattress & Box Spring",
    title: "Mattress Disposal & Removal | Morris Junk Removal",
    description:
      "Mattress and box spring removal in Warren County, MO — facility rules, soiling limits, and bundling with other junk.",
    keywords: ["mattress disposal", "mattress removal Missouri"],
    acceptance: "usually",
    canRemove: "Yes — mattresses and box springs in most cases.",
    specialHandling: "Facility rules may apply. Heavily soiled pieces can be restricted.",
    recycling: "Some facilities accept mattresses for recycling; availability varies.",
    donation: "Rare unless a receiver specifically accepts clean mattresses.",
    manualReview: "When heavily soiled or combined with large estate loads.",
    pricingFactors: ["Piece count", "Floor / stairs", "Bundled with other items"],
    relatedServices: ["mattress-removal", "furniture-removal"],
    relatedGuides: ["what-can-we-remove", "how-recycling-works"],
    relatedItems: ["couch-sofa"],
    faqs: [
      {
        q: "Can mattresses go with a garage cleanout?",
        a: "Yes — combining items into one visit is usually more efficient.",
      },
    ],
  },
  {
    slug: "refrigerator",
    name: "Refrigerator",
    title: "Refrigerator Disposal & Removal | Morris Junk Removal",
    description:
      "Refrigerator removal and disposal guidance for Warren County — empty units, freon rules, and metal recycling when available.",
    keywords: ["refrigerator disposal", "fridge removal Missouri"],
    acceptance: "special",
    canRemove: "Yes when empty and accessible. Freon appliances follow facility requirements.",
    specialHandling: "Must be empty. Freon handling rules may apply — we follow facility requirements.",
    recycling: "Metal recycling is common when facilities accept the unit.",
    donation: "Working units may be donation candidates if a receiver accepts them.",
    manualReview: "Yes for freon units, non-running units, or difficult access.",
    pricingFactors: ["Size", "Stairs", "Running condition", "Freon handling"],
    relatedServices: ["appliance-removal"],
    relatedGuides: ["how-recycling-works", "prepare-for-junk-removal"],
    relatedItems: ["washer-dryer", "freezer", "water-heater"],
    faqs: [
      {
        q: "Do you disconnect refrigerators?",
        a: "Unplug and empty before arrival. Hardwired or water-line disconnects should be done by a qualified person unless we agree otherwise in writing.",
      },
    ],
  },
  {
    slug: "washer-dryer",
    name: "Washer & Dryer",
    title: "Washer & Dryer Removal | Morris Junk Removal",
    description: "Washer and dryer haul-away for homes and rentals in Warren County and nearby Missouri.",
    keywords: ["washer dryer removal", "appliance haul away"],
    acceptance: "usually",
    canRemove: "Yes — standard washers and dryers when disconnected and empty.",
    specialHandling: "Gas dryers need proper disconnect by a qualified person before pickup.",
    recycling: "Metal recycling is often available.",
    donation: "Working sets may be donation candidates when accepted.",
    manualReview: "Basement units with tight stairs may need review.",
    pricingFactors: ["Pair vs single", "Stairs", "Gas vs electric"],
    relatedServices: ["appliance-removal"],
    relatedGuides: ["prepare-for-junk-removal"],
    relatedItems: ["refrigerator", "freezer"],
    faqs: [{ q: "Do you unhook water lines?", a: "Have units disconnected and drained before we arrive unless scoped otherwise." }],
  },
  {
    slug: "freezer",
    name: "Freezer",
    title: "Freezer Removal | Morris Junk Removal",
    description: "Chest and upright freezer removal with freon and access notes for Missouri homes.",
    keywords: ["freezer removal", "freezer disposal"],
    acceptance: "special",
    canRemove: "Yes when empty. Freon rules may apply.",
    specialHandling: "Empty completely. Chest freezers in basements need path measurements.",
    recycling: "Metal recycling when accepted.",
    donation: "Possible for working units if a receiver accepts them.",
    manualReview: "Yes for freon and tight access.",
    pricingFactors: ["Chest vs upright", "Stairs", "Freon handling"],
    relatedServices: ["appliance-removal"],
    relatedGuides: ["how-recycling-works"],
    relatedItems: ["refrigerator"],
    faqs: [{ q: "Can food stay inside?", a: "No — empty and defrost before pickup." }],
  },
  {
    slug: "water-heater",
    name: "Water Heater",
    title: "Water Heater Removal | Morris Junk Removal",
    description: "Water heater haul-away after professional disconnect for Warren County properties.",
    keywords: ["water heater removal", "water heater disposal"],
    acceptance: "special",
    canRemove: "Yes after a qualified person disconnects utilities and drains the unit.",
    specialHandling: "We do not perform plumbing or gas disconnects unless separately agreed in writing.",
    recycling: "Metal recycling is common.",
    donation: "Uncommon.",
    manualReview: "Yes — confirm disconnect status and access.",
    pricingFactors: ["Size", "Location", "Stairs"],
    relatedServices: ["appliance-removal", "construction-debris-removal"],
    relatedGuides: ["construction-cleanup-guide"],
    relatedItems: ["refrigerator"],
    faqs: [
      {
        q: "Will you cut pipes?",
        a: "No. Have a qualified person disconnect and drain before our arrival.",
      },
    ],
  },
  {
    slug: "tv-electronics",
    name: "TV & Electronics",
    title: "TV & Electronics Removal | Morris Junk Removal",
    description:
      "TV and electronics removal when e-waste options are available — honest acceptance for Warren County jobs.",
    keywords: ["electronics removal", "TV disposal Missouri"],
    acceptance: "sometimes",
    canRemove: "Often yes when an appropriate e-waste path is available.",
    specialHandling: "Identify TVs, computers, printers, and peripherals in your estimate request.",
    recycling: "Through e-waste channels when accepted — not guaranteed every day.",
    donation: "Working electronics may be donation candidates; damaged units usually are not.",
    manualReview: "Yes when volume is high or facilities are restricted.",
    pricingFactors: ["Count", "Screen size", "Specialty routing"],
    relatedServices: ["furniture-removal", "commercial-cleanouts"],
    relatedGuides: ["how-recycling-works", "what-we-cannot-take"],
    relatedItems: ["batteries"],
    faqs: [
      {
        q: "Do you wipe hard drives?",
        a: "No. Remove or destroy drives yourself before pickup if data security matters.",
      },
    ],
  },
  {
    slug: "hot-tub",
    name: "Hot Tub",
    title: "Hot Tub Removal | Morris Junk Removal",
    description: "Hot tub removal with access, weight, and disposal notes for Missouri properties.",
    keywords: ["hot tub removal", "spa removal"],
    acceptance: "special",
    canRemove: "Often yes after draining and confirming access for a trailer.",
    specialHandling: "Must be drained. Gate width, slope, and crane needs matter — photos required.",
    recycling: "Components may be separated when practical; intact recycling is uncommon.",
    donation: "Rare.",
    manualReview: "Almost always — weight and access.",
    pricingFactors: ["Size", "Access", "Disassembly needs"],
    relatedServices: ["hot-tub-shed-removal"],
    relatedGuides: ["photo-estimate-tips", "how-junk-removal-pricing-works"],
    relatedItems: ["shed-cleanup"],
    faqs: [{ q: "Do you drain hot tubs?", a: "Have the tub drained before arrival unless we agree otherwise in writing." }],
  },
  {
    slug: "piano",
    name: "Piano",
    title: "Piano Removal | Morris Junk Removal",
    description: "Piano removal with manual review for stairs, weight, and path clearance in Warren County.",
    keywords: ["piano removal", "piano junk removal"],
    acceptance: "special",
    canRemove: "Sometimes — uprights more often than grands. Manual review required.",
    specialHandling: "Weight, stairs, and turns determine feasibility. Photos and measurements required.",
    recycling: "Limited; wood and metal may be separated in some cases.",
    donation: "Possible if a receiver wants a working instrument — not guaranteed.",
    manualReview: "Always.",
    pricingFactors: ["Upright vs grand", "Stairs", "Path width", "Crew size"],
    relatedServices: ["furniture-removal", "estate-cleanouts"],
    relatedGuides: ["estate-cleanout-checklist", "photo-estimate-tips"],
    relatedItems: ["safe", "pool-table"],
    faqs: [
      {
        q: "Can you take a grand piano upstairs?",
        a: "Often no. Share photos and floor plans early — we will accept or decline honestly.",
      },
    ],
  },
  {
    slug: "pool-table",
    name: "Pool Table",
    title: "Pool Table Removal | Morris Junk Removal",
    description: "Pool table removal with disassembly and access notes for Missouri homes.",
    keywords: ["pool table removal"],
    acceptance: "special",
    canRemove: "Often yes when disassembled or path allows.",
    specialHandling: "Slate tables are heavy — expect disassembly discussion.",
    recycling: "Limited.",
    donation: "Possible if usable and a receiver accepts.",
    manualReview: "Yes.",
    pricingFactors: ["Slate vs non-slate", "Stairs", "Disassembly"],
    relatedServices: ["furniture-removal"],
    relatedGuides: ["prepare-for-junk-removal"],
    relatedItems: ["piano", "exercise-equipment"],
    faqs: [{ q: "Do you disassemble pool tables?", a: "When scoped. Tell us brand/size and whether slate is present." }],
  },
  {
    slug: "safe",
    name: "Safe",
    title: "Safe Removal | Morris Junk Removal",
    description: "Home and office safe removal with weight and path review.",
    keywords: ["safe removal", "safe haul away"],
    acceptance: "special",
    canRemove: "Sometimes — depends on weight and path.",
    specialHandling: "Exact weight and stair count required. Some safes exceed safe crew limits.",
    recycling: "Metal recycling when accepted.",
    donation: "Uncommon.",
    manualReview: "Always.",
    pricingFactors: ["Weight", "Stairs", "Anchoring"],
    relatedServices: ["furniture-removal", "commercial-cleanouts"],
    relatedGuides: ["photo-estimate-tips"],
    relatedItems: ["piano"],
    faqs: [{ q: "Do you open locked safes?", a: "No. Unlock or have a locksmith handle access before pickup." }],
  },
  {
    slug: "exercise-equipment",
    name: "Exercise Equipment",
    title: "Exercise Equipment Removal | Morris Junk Removal",
    description: "Treadmill, elliptical, and weight equipment removal for Warren County homes.",
    keywords: ["treadmill removal", "exercise equipment junk removal"],
    acceptance: "usually",
    canRemove: "Yes for most home gym equipment when path allows.",
    specialHandling: "Treadmills on stairs need measurements. Disassemble when possible.",
    recycling: "Metal components may be recoverable.",
    donation: "Working equipment may be donation candidates.",
    manualReview: "For commercial gym volume or extreme weight.",
    pricingFactors: ["Item type", "Stairs", "Disassembly"],
    relatedServices: ["furniture-removal", "garage-cleanouts"],
    relatedGuides: ["garage-cleanout-checklist"],
    relatedItems: ["lawn-mower"],
    faqs: [{ q: "Do you take free weights?", a: "Yes when boxed or staged safely for loading." }],
  },
  {
    slug: "lawn-mower",
    name: "Lawn Mower",
    title: "Lawn Mower Removal | Morris Junk Removal",
    description: "Lawn mower and small outdoor equipment removal — drain fuel notes for Missouri pickups.",
    keywords: ["lawn mower removal", "mower junk removal"],
    acceptance: "usually",
    canRemove: "Yes for most push and riding mowers when fluids are handled per our instructions.",
    specialHandling: "Drain fuel when requested. Riding mowers need trailer access.",
    recycling: "Metal scrap is often available.",
    donation: "Working mowers may be donation candidates.",
    manualReview: "For large ag equipment — that may be a hauling job instead.",
    pricingFactors: ["Push vs riding", "Fuel status", "Access"],
    relatedServices: ["garage-cleanouts"],
    relatedGuides: ["what-can-we-remove"],
    relatedItems: ["grill", "yard-debris"],
    faqs: [
      {
        q: "Is a tractor junk removal or hauling?",
        a: "Larger tractors are usually Morris Hauling territory. Ask with photos and weight.",
      },
    ],
  },
  {
    slug: "grill",
    name: "Grill",
    title: "Grill Removal | Morris Junk Removal",
    description: "Gas and charcoal grill removal for patio and garage cleanouts.",
    keywords: ["grill removal", "bbq junk removal"],
    acceptance: "usually",
    canRemove: "Yes — disconnect propane tanks and remove fuel canisters first.",
    specialHandling: "Propane tanks may be restricted — tell us what you have.",
    recycling: "Metal recycling common.",
    donation: "Possible if usable.",
    manualReview: "For built-in outdoor kitchens.",
    pricingFactors: ["Size", "Built-in vs freestanding"],
    relatedServices: ["garage-cleanouts", "furniture-removal"],
    relatedGuides: ["prepare-for-junk-removal"],
    relatedItems: ["lawn-mower"],
    faqs: [{ q: "Can propane tanks stay attached?", a: "Remove tanks before pickup unless we confirm otherwise." }],
  },
  {
    slug: "tires",
    name: "Tires",
    title: "Tire Removal | Morris Junk Removal",
    description: "Tire removal through appropriate facilities when accepted — honest limits for Missouri jobs.",
    keywords: ["tire removal", "tire disposal junk removal"],
    acceptance: "special",
    canRemove: "Sometimes — tires often need specialty facilities and may have per-tire fees.",
    specialHandling: "Count and size matter. On-rim vs off-rim can change acceptance.",
    recycling: "Through tire facilities when available.",
    donation: "No.",
    manualReview: "Yes.",
    pricingFactors: ["Count", "Size", "On-rim", "Facility fees"],
    relatedServices: ["garage-cleanouts"],
    relatedGuides: ["how-recycling-works", "what-we-cannot-take"],
    relatedItems: ["batteries"],
    faqs: [
      {
        q: "Do you take a whole trailer of tires?",
        a: "Ask first. Large tire volumes may be declined or priced as specialty routing.",
      },
    ],
  },
  {
    slug: "batteries",
    name: "Batteries",
    title: "Battery Disposal Guidance | Morris Junk Removal",
    description: "Battery handling during junk removal — specialty routing and what not to mix in household piles.",
    keywords: ["battery disposal junk removal"],
    acceptance: "special",
    canRemove: "Sometimes via appropriate collection points — not mixed casually into general junk.",
    specialHandling: "Identify car batteries, lithium packs, and household batteries separately.",
    recycling: "Through specialty channels when available.",
    donation: "No.",
    manualReview: "Yes.",
    pricingFactors: ["Type", "Quantity", "Specialty drop fees"],
    relatedServices: ["garage-cleanouts"],
    relatedGuides: ["what-we-cannot-take", "how-recycling-works"],
    relatedItems: ["tires", "tv-electronics"],
    faqs: [
      {
        q: "Can batteries ride with a garage cleanout?",
        a: "Tell us in advance. Some batteries cannot travel in the same stream as general junk.",
      },
    ],
  },
  {
    slug: "paint",
    name: "Paint",
    title: "Paint Disposal Guidance | Morris Junk Removal",
    description: "Paint can acceptance varies — sealed, empty, and latex vs oil rules for Missouri junk jobs.",
    keywords: ["paint disposal junk removal"],
    acceptance: "rarely",
    canRemove: "Sometimes for empty or specifically accepted cans — never assume.",
    specialHandling: "List type (latex/oil), sealed vs empty, and quantity.",
    recycling: "Limited; household hazardous rules apply.",
    donation: "Unopened usable paint may have community reuse options — not guaranteed through us.",
    manualReview: "Always.",
    pricingFactors: ["Type", "Quantity", "Facility rules"],
    relatedServices: ["garage-cleanouts", "construction-debris-removal"],
    relatedGuides: ["what-we-cannot-take"],
    relatedItems: ["construction-debris"],
    faqs: [
      {
        q: "Can I leave paint in the garage pile?",
        a: "Call it out separately. Unexpected paint is a common reason loads get delayed.",
      },
    ],
  },
  {
    slug: "yard-debris",
    name: "Yard Debris",
    title: "Yard Debris Removal | Morris Junk Removal",
    description: "Yard waste and brush removal when facilities accept it — keep it separated from household junk.",
    keywords: ["yard debris removal", "brush removal Missouri"],
    acceptance: "sometimes",
    canRemove: "Often yes when separated and facilities accept yard waste.",
    specialHandling: "Keep yard waste out of household trash bags. Watch for treated lumber mixed in.",
    recycling: "Yard waste streams when available.",
    donation: "No.",
    manualReview: "For storm volumes or mixed loads.",
    pricingFactors: ["Volume", "Separation", "Facility acceptance"],
    relatedServices: ["garage-cleanouts"],
    relatedGuides: ["spring-cleaning-guide", "how-recycling-works"],
    relatedItems: ["construction-debris"],
    faqs: [
      {
        q: "Do you chip brush on site?",
        a: "No — we haul. Chipping is a different service.",
      },
    ],
  },
  {
    slug: "construction-debris",
    name: "Construction Debris",
    title: "Construction Debris Removal | Morris Junk Removal",
    description:
      "Construction and renovation debris removal — separated materials vs mixed loads for Warren County projects.",
    keywords: ["construction debris removal", "renovation junk removal"],
    acceptance: "usually",
    canRemove: "Yes for many renovation loads when access and materials are clear.",
    specialHandling: "Separated wood, metal, cardboard, and concrete may route differently than mixed debris.",
    recycling: "Possible for clean separated streams; mixed debris often limited.",
    donation: "Usable building materials sometimes — not guaranteed.",
    manualReview: "For heavy concrete, roofing, or uncertain materials.",
    pricingFactors: ["Volume", "Weight", "Separation", "Site access"],
    relatedServices: ["construction-debris-removal", "commercial-cleanouts"],
    relatedGuides: ["construction-cleanup-guide", "dumpster-vs-junk-removal"],
    relatedItems: ["concrete-brick", "yard-debris"],
    faqs: [
      {
        q: "Is this a dumpster job?",
        a: "Multi-day contractor loading often needs a dumpster rental. Same-day haul-away is our model.",
      },
    ],
  },
  {
    slug: "concrete-brick",
    name: "Concrete, Brick & Asphalt",
    title: "Concrete & Brick Removal | Morris Junk Removal",
    description: "Concrete, brick, and asphalt removal when weight and facility acceptance allow.",
    keywords: ["concrete removal", "brick disposal"],
    acceptance: "special",
    canRemove: "Sometimes — weight and facility rules decide.",
    specialHandling: "Heavy loads need accurate volume estimates. Photos and measurements required.",
    recycling: "When clean and accepted by masonry recyclers.",
    donation: "Uncommon.",
    manualReview: "Always for larger piles.",
    pricingFactors: ["Tons/volume", "Contamination", "Access"],
    relatedServices: ["construction-debris-removal"],
    relatedGuides: ["construction-cleanup-guide", "how-recycling-works"],
    relatedItems: ["construction-debris"],
    faqs: [
      {
        q: "Do you jackhammer concrete?",
        a: "No. We haul broken material. Demolition is separate.",
      },
    ],
  },
  {
    slug: "office-furniture",
    name: "Office Furniture",
    title: "Office Furniture Removal | Morris Junk Removal",
    description: "Office desk, cubicle, and chair removal for commercial cleanouts in our Missouri service area.",
    keywords: ["office furniture removal", "cubicle removal"],
    acceptance: "usually",
    canRemove: "Yes for most desks, chairs, cubicles, and filing cabinets.",
    specialHandling: "Elevator reservations and after-hours windows help occupied buildings.",
    recycling: "Metal components may be recoverable.",
    donation: "Usable office furniture may be donation candidates.",
    manualReview: "For full-floor cubicle farms.",
    pricingFactors: ["Volume", "Elevator access", "Disassembly"],
    relatedServices: ["commercial-cleanouts", "furniture-removal"],
    relatedGuides: ["commercial-cleanout-planning", "donation-vs-disposal"],
    relatedItems: ["couch-sofa", "tv-electronics"],
    faqs: [
      {
        q: "Can you work after hours?",
        a: "Ask when requesting an estimate. After-hours capacity is limited and must be confirmed.",
      },
    ],
  },
  {
    slug: "shed-cleanup",
    name: "Shed Cleanup",
    title: "Shed Cleanup & Removal Debris | Morris Junk Removal",
    description: "Shed contents cleanout and shed debris haul-away after takedown in Warren County.",
    keywords: ["shed cleanout", "shed removal debris"],
    acceptance: "usually",
    canRemove: "Yes for shed contents; full shed structures need access and debris notes.",
    specialHandling: "If the shed is being demolished, confirm who demolishes and what we haul.",
    recycling: "Wood and metal may be separable when practical.",
    donation: "Usable contents maybe; structures rarely.",
    manualReview: "For large structures or unclear demolition scope.",
    pricingFactors: ["Contents vs structure", "Access", "Materials"],
    relatedServices: ["hot-tub-shed-removal", "garage-cleanouts"],
    relatedGuides: ["garage-cleanout-checklist"],
    relatedItems: ["hot-tub", "yard-debris"],
    faqs: [
      {
        q: "Do you demolish sheds?",
        a: "Debris haul-away is our core offer. Demolition must be scoped separately if offered at all.",
      },
    ],
  },
];

export function getItem(slug: string) {
  return AUTHORITY_ITEMS.find((i) => i.slug === slug);
}

export function allItemSlugs() {
  return AUTHORITY_ITEMS.map((i) => i.slug);
}

export const ACCEPTANCE_LABELS: Record<ItemAcceptance, string> = {
  usually: "Usually accepted",
  sometimes: "Sometimes — depends on facility rules",
  special: "Special handling / review",
  rarely: "Rarely — ask first",
  no: "Not accepted",
};
