-- Disposal network expansion: verified MO/IL facilities + expandable county registry
-- Generated from lib/data/disposal-network — do not invent tip fees; null pricing means call ahead.
-- Replaces incorrect 033 reference rows that did not match DNR / operator sources.

-- ---------------------------------------------------------------------------
-- Schema: expandable facility fields
-- ---------------------------------------------------------------------------
-- App + network catalog use per_item; original 002 check omitted it.
alter table public.dump_sites drop constraint if exists dump_sites_fee_type_check;
alter table public.dump_sites add constraint dump_sites_fee_type_check
  check (fee_type in ('flat', 'weight', 'volume', 'mixed', 'per_item'));

alter table public.dump_sites add column if not exists facility_type text;
alter table public.dump_sites add column if not exists commercial_accepted boolean;
alter table public.dump_sites add column if not exists appointment_required boolean not null default false;
alter table public.dump_sites add column if not exists residency_restriction text
  check (residency_restriction is null or residency_restriction in (
    'none', 'county_residents', 'city_residents', 'account_holders', 'unknown'
  ));
alter table public.dump_sites add column if not exists special_requirements text;
alter table public.dump_sites add column if not exists operational_notes text;
alter table public.dump_sites add column if not exists scale_available boolean;
alter table public.dump_sites add column if not exists payment_methods text[] not null default '{}';
alter table public.dump_sites add column if not exists public_pricing_notes text;
alter table public.dump_sites add column if not exists commercial_pricing_notes text;
alter table public.dump_sites add column if not exists pricing_unknown boolean not null default true;
alter table public.dump_sites add column if not exists verification_status text
  check (verification_status is null or verification_status in (
    'verified', 'partial', 'needs_call', 'needs_geocode'
  ));
alter table public.dump_sites add column if not exists verification_sources jsonb not null default '[]'::jsonb;
alter table public.dump_sites add column if not exists verified_at timestamptz;
alter table public.dump_sites add column if not exists pricing_verified_at timestamptz;
alter table public.dump_sites add column if not exists geocode_source text;

create index if not exists dump_sites_county_idx on public.dump_sites(company_id, state, county);
create index if not exists dump_sites_facility_type_idx on public.dump_sites(company_id, facility_type);
create index if not exists dump_sites_verification_idx on public.dump_sites(company_id, verification_status);

-- ---------------------------------------------------------------------------
-- Coverage counties (grow without redesign)
-- ---------------------------------------------------------------------------
create table if not exists public.disposal_coverage_counties (
  id text primary key,
  company_id text not null references public.companies(id) on delete cascade,
  state text not null check (state in ('MO', 'IL')),
  county text not null,
  tier text not null check (tier in ('core', 'expansion', 'adjacent')),
  status text not null check (status in ('active', 'planned', 'no_local_msw_facility')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, state, county)
);

create index if not exists disposal_coverage_counties_company_idx
  on public.disposal_coverage_counties(company_id, state, tier);

alter table public.disposal_coverage_counties enable row level security;

drop policy if exists "disposal_coverage_counties_access" on public.disposal_coverage_counties;
create policy "disposal_coverage_counties_access" on public.disposal_coverage_counties for all
  using (company_id = current_setting('app.company_id', true))
  with check (company_id = current_setting('app.company_id', true));

-- ---------------------------------------------------------------------------
-- Remove incorrect legacy reference facilities
-- ---------------------------------------------------------------------------
delete from public.dump_sites
where company_id = 'morris-hauling'
  and id in ('ref-st-charles-recycle-works', 'ref-wentzville-srf', 'ref-lincoln-county-transfer', 'ref-warren-county-sanitary', 'ref-franklin-county-sanitary', 'ref-jefferson-county-sanitary', 'ref-o-fallon-waste', 'ref-lake-st-louis-transfer');


-- ---------------------------------------------------------------------------
-- Seed coverage counties
-- ---------------------------------------------------------------------------
insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('mo-warren', 'morris-hauling', 'MO', 'Warren', 'core', 'no_local_msw_facility', 'No DNR-listed operating sanitary landfill or transfer station in-county. Primary MSW tip: Meridian Foristell. Recycling: East Central Missouri Recycling Center (Warrenton).', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('mo-st-charles', 'morris-hauling', 'MO', 'St. Charles', 'core', 'active', 'Meridian Foristell transfer; O''Fallon city transfer (resident-oriented); Recycle Works Central/West.', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('mo-lincoln', 'morris-hauling', 'MO', 'Lincoln', 'core', 'active', 'Meridian Winfield transfer (DNR-listed).', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('mo-franklin', 'morris-hauling', 'MO', 'Franklin', 'core', 'active', 'City of Washington (Struckhoff) sanitary landfill (DNR-listed).', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('mo-jefferson', 'morris-hauling', 'MO', 'Jefferson', 'expansion', 'active', 'WM DeSoto and Kimmswick transfer stations (DNR-listed). No operating sanitary landfill in-county on DNR list.', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('mo-st-louis', 'morris-hauling', 'MO', 'St. Louis', 'expansion', 'active', 'Champ Landfill; Bridgeton, Valley Park (FW Disposal), University City transfers; Rock Hill demolition landfill.', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('mo-st-louis-city', 'morris-hauling', 'MO', 'St. Louis City', 'expansion', 'active', 'Multiple DNR-listed city transfer/processing facilities — verify commercial access per site before routing.', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('mo-washington', 'morris-hauling', 'MO', 'Washington', 'expansion', 'active', 'Timber Ridge Landfill (Richwoods); CWI-Potosi transfer (Cadet) — geocode/confirm before first use.', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('mo-st-francois', 'morris-hauling', 'MO', 'St. Francois', 'expansion', 'active', 'St. Francois County Solid Waste Transfer Station (Park Hills).', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('mo-crawford', 'morris-hauling', 'MO', 'Crawford', 'expansion', 'active', 'Prairie Valley Landfill (Cuba).', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('mo-gasconade', 'morris-hauling', 'MO', 'Gasconade', 'adjacent', 'no_local_msw_facility', 'No DNR-listed operating transfer/sanitary landfill in-county. Route to Franklin (Struckhoff) or Crawford (Prairie Valley).', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('mo-montgomery', 'morris-hauling', 'MO', 'Montgomery', 'adjacent', 'no_local_msw_facility', 'No DNR-listed operating transfer/sanitary landfill in-county. Recycling via East Central Missouri Recycling Center service area; MSW tip via Meridian Foristell or Struckhoff.', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('il-st-clair', 'morris-hauling', 'IL', 'St. Clair', 'expansion', 'active', 'Milam RDF (East St. Louis); Cottonwood Hills RDF (Marissa) — St. Clair County Health / WM.', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('il-madison', 'morris-hauling', 'IL', 'Madison', 'expansion', 'active', 'Roxana Landfill (Edwardsville) — Republic Services / IEPA NPDES facility.', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

insert into public.disposal_coverage_counties (id, company_id, state, county, tier, status, notes, updated_at)
values ('il-monroe', 'morris-hauling', 'IL', 'Monroe', 'expansion', 'active', 'Monroe County Recycling Center / dump site (Waterloo) — county health department; confirm commercial hauler rules before routing.', now())
on conflict (id) do update set
  state = excluded.state,
  county = excluded.county,
  tier = excluded.tier,
  status = excluded.status,
  notes = excluded.notes,
  updated_at = now();

-- ---------------------------------------------------------------------------
-- Seed verified facilities (20)
-- ---------------------------------------------------------------------------
insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-meridian-foristell-transfer', 'morris-hauling', 'Meridian Waste - Foristell Hauling & Transfer Station', '17900 Veterans Memorial Parkway', 'Foristell', 'MO', '63348', 'St. Charles',
  38.813946, -90.9455244, '(314) 291-3131', 'https://www.meridianwaste.com/mo/foristell/meridian-waste-foristell-hauling-transfer-station/',
  'transfer_station', 'both', true, false, 'none',
  '{"mon":"5:00 AM – 4:30 PM","tue":"5:00 AM – 4:30 PM","wed":"5:00 AM – 4:30 PM","thu":"5:00 AM – 4:30 PM","fri":"5:00 AM – 4:30 PM","sat":"Closed","sun":"Closed"}'::jsonb, '{"New Year''s Day","Memorial Day","Independence Day","Labor Day","Thanksgiving Day","Christmas Day"}'::text[], '{"mixed_junk","household_trash","furniture","mattresses","commercial_waste","construction_demolition"}'::text[], '{"Hazardous waste","Waste oils / oil filters / oil tanks","Gasoline cans & tanks","Mercury devices / PCBs","Paint","Asbestos","Tires","Propane tanks","Liquids or sludge","Automobile parts","Batteries","Biomedical waste","Yard waste / dirt / mulch / stumps / rocks / land clearing debris","Appliances","Chain link fencing"}'::text[],
  'Hard hat and OSHA reflective vest required (available for purchase). All loads must be tarped or incur a fee. Credit application required to establish an account. One-ton minimum charge per load for non-accountholders.', 'Primary western St. Charles / Warren / Lincoln corridor transfer. Operator publishes excluded-waste list; tip rates not published online — call for commercial rate sheet.', 'Primary western St. Charles / Warren / Lincoln corridor transfer. Operator publishes excluded-waste list; tip rates not published online — call for commercial rate sheet.', 'Best default MSW tip for Warrenton-area jobs when open. Confirm current commercial ton rate before quoting large loads. Yard waste and appliances must go elsewhere.',
  'weight', null, null, null, true,
  'Tip rates not published on operator site as of verification date.', 'One-ton minimum for non-accountholders. Account setup via credit application. Call (314) 291-3131 for current commercial rates.',
  null, null, null, null,
  true, '{"credit_card","check"}'::text[],
  'partial', '[{"label":"Meridian Waste Foristell facility page","url":"https://www.meridianwaste.com/mo/foristell/meridian-waste-foristell-hauling-transfer-station/","retrievedAt":"2026-07-10"},{"label":"Missouri DNR operating transfer stations","url":"https://dnr.mo.gov/waste-recycling/sites-regulated-facilities/operating-solid-waste-processing","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'nominatim_openstreetmap',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-meridian-winfield-transfer', 'morris-hauling', 'Meridian Waste - Winfield Transfer Station', '751 S Highway 79', 'Winfield', 'MO', '63389', 'Lincoln',
  39.00604733, -90.73919611, '(314) 291-3131', 'https://www.meridianwaste.com/mo/winfield/meridian-waste-winfield-transfer-station/',
  'transfer_station', 'both', true, false, 'none',
  '{"mon":"6:30 AM – 3:30 PM (closed 11:30 AM – 12:00 PM lunch)","tue":"6:30 AM – 3:30 PM (closed 11:30 AM – 12:00 PM lunch)","wed":"6:30 AM – 3:30 PM (closed 11:30 AM – 12:00 PM lunch)","thu":"6:30 AM – 3:30 PM (closed 11:30 AM – 12:00 PM lunch)","fri":"6:30 AM – 3:30 PM (closed 11:30 AM – 12:00 PM lunch)","sat":"Closed","sun":"Closed"}'::jsonb, '{"New Year''s Day","Memorial Day","Independence Day","Labor Day","Thanksgiving Day","Christmas Day"}'::text[], '{"mixed_junk","household_trash","furniture","mattresses","commercial_waste"}'::text[], '{"Hazardous waste","Waste oils / oil filters","Paint","Asbestos","Tires","Propane tanks","Liquids or sludge","Batteries","Yard waste / dirt / rocks / stumps","Appliances"}'::text[],
  'Hard hat and reflective vest required. Loads must be tarped. No cash. One-ton minimum for non-accountholders. Closed daily for lunch 11:30–12:00.', 'DNR-listed Meridian Waste Missouri LLC-Winfield Transfer. Same excluded-waste pattern as Foristell.', 'DNR-listed Meridian Waste Missouri LLC-Winfield Transfer. Same excluded-waste pattern as Foristell.', 'Prefer for northern Lincoln County jobs when open; watch lunch closure.',
  'weight', null, null, null, true,
  null, 'Call (314) 291-3131 for commercial rates. One-ton minimum non-account.',
  null, null, null, null,
  true, '{"credit_card","check"}'::text[],
  'partial', '[{"label":"Meridian Waste Winfield facility page","url":"https://www.meridianwaste.com/mo/winfield/meridian-waste-winfield-transfer-station/","retrievedAt":"2026-07-10"},{"label":"Missouri DNR operating transfer stations","url":"https://dnr.mo.gov/waste-recycling/sites-regulated-facilities/operating-solid-waste-processing","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'us_census_geocoder',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-ofallon-transfer', 'morris-hauling', 'City of O''Fallon Regional Waste Transfer Station and Recycling Center', '1572 Progress West Lane', 'O''Fallon', 'MO', '63366', 'St. Charles',
  38.8075521, -90.7607961, '(636) 272-0477', 'https://ofallon.mo.us/bulk-waste',
  'transfer_station', 'public', false, false, 'city_residents',
  '{"mon":"Bulk drop-off by scheduled city events only — call Environmental Services","tue":"Bulk drop-off by scheduled city events only — call Environmental Services","wed":"Bulk drop-off by scheduled city events only — call Environmental Services","thu":"Bulk drop-off by scheduled city events only — call Environmental Services","fri":"Bulk drop-off by scheduled city events only — call Environmental Services","sat":"Scheduled bulk drop-off days typically 7:00 AM – 3:00 PM (confirm calendar)","sun":"Closed"}'::jsonb, '{}'::text[], '{"furniture","mattresses","electronics","mixed_junk"}'::text[], '{"Commercial vehicles","Box trucks","Trailers larger than 10 feet","Rental vehicles"}'::text[],
  'Public bulk drop-off is for O''Fallon trash-service customers with photo ID. One car/pickup/small trailer (≤10 ft) per address per event. Residents unload their own items. Commercial vehicles turned away.', 'DNR-listed City of O''Fallon Regional Waste Transfer Station. Not a general commercial tip for Morris Services loads.', 'DNR-listed City of O''Fallon Regional Waste Transfer Station. Not a general commercial tip for Morris Services loads.', 'Do not route commercial junk loads here. Keep in DB for material/residency awareness and customer referrals only.',
  'flat', null, null, null, true,
  'Bulk drop-off free for enrolled O''Fallon residents on scheduled event days.', 'Commercial customers not accepted for bulk drop-off / roll-off residential program.',
  null, 'Trailers larger than 10 feet not allowed on bulk drop-off days.', 'No box trucks, rental vehicles, or commercial vehicles on bulk drop-off days.', null,
  null, '{}'::text[],
  'verified', '[{"label":"City of O''Fallon bulk waste page","url":"https://ofallon.mo.us/bulk-waste","retrievedAt":"2026-07-10"},{"label":"Missouri DNR operating transfer stations","url":"https://dnr.mo.gov/waste-recycling/sites-regulated-facilities/operating-solid-waste-processing","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, '2026-07-10'::timestamptz, 'nominatim_openstreetmap',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-recycle-works-central', 'morris-hauling', 'St. Charles County Recycle Works - Central', '60 Triad South Drive', 'St. Charles', 'MO', '63304', 'St. Charles',
  38.7415922, -90.6208744, '(636) 949-7900 ext. 4273', 'https://www.sccmo.org/892/Recycle-Works---Central',
  'recycling_center', 'public', false, true, 'county_residents',
  '{"mon":"8:30 AM – 4:30 PM","tue":"8:30 AM – 4:30 PM","wed":"8:30 AM – 4:30 PM","thu":"8:30 AM – 4:30 PM","fri":"8:30 AM – 4:30 PM","sat":"8:30 AM – 4:30 PM","sun":"Closed"}'::jsonb, '{"County-observed holidays"}'::text[], '{"recycling","electronics","cardboard","batteries","oil","paint","hazardous_waste"}'::text[], '{"Latex / water-based paint","Mattresses and box springs","Medical waste","Explosives / ammunition","Business / government waste (HHW program)","Plastic bags / film","Polystyrene"}'::text[],
  'HHW accepted May–September, Tue–Fri 9:00 AM–3:00 PM from St. Charles County residents only; appointments required for hazardous household chemicals. HHW: $25 first 50 lb then $1/lb; non-resident fee $20 (per county fee sheet).', 'County recycling / HHW drop-off — not a MSW transfer station. Prior seed data incorrectly treated this as a general junk landfill.', 'County recycling / HHW drop-off — not a MSW transfer station. Prior seed data incorrectly treated this as a general junk landfill.', 'Use for separated e-waste / recycling / seasonal HHW only. Never send mixed commercial junk loads here.',
  'mixed', 25, null, 25, false,
  'HHW $25 up to 50 lb then $1/lb (May–Sep). Fluorescent bulb commercial rates published on county site. Most recycling free for residents — confirm current fee sheet at health.sccmo.org.', 'HHW program is for residents; commercial fluorescent bulb fees published. Confirm before routing any commercial load.',
  null, null, null, null,
  false, '{"cash","check","credit_card"}'::text[],
  'verified', '[{"label":"St. Charles County Recycle Works Central","url":"https://www.sccmo.org/892/Recycle-Works---Central","retrievedAt":"2026-07-10"},{"label":"Recycle Works fee sheet (county archive)","url":"https://mo-stcharlescounty.civicplus.com/Archive/ViewFile/Item/4998","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, '2026-07-10'::timestamptz, 'nominatim_openstreetmap',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-recycle-works-west', 'morris-hauling', 'St. Charles County Recycle Works - West', '2110 E Pitman Avenue', 'Wentzville', 'MO', '63385', 'St. Charles',
  38.8088384, -90.8088689, '(636) 949-7900 ext. 4267', 'https://www.sccmo.org/892/Recycle-Works---Central',
  'recycling_center', 'public', false, true, 'county_residents',
  '{"mon":"8:30 AM – 4:30 PM","tue":"8:30 AM – 4:30 PM","wed":"8:30 AM – 4:30 PM","thu":"8:30 AM – 4:30 PM","fri":"8:30 AM – 4:30 PM","sat":"8:30 AM – 4:30 PM","sun":"Closed"}'::jsonb, '{"County-observed holidays"}'::text[], '{"recycling","electronics","cardboard","batteries","oil","paint","hazardous_waste"}'::text[], '{"Latex / water-based paint","Mattresses and box springs","Medical waste","Business / government waste (HHW program)"}'::text[],
  'Same Recycle Works program rules as Central. HHW seasonal hours and resident restrictions apply — confirm West site HHW availability before routing.', 'Western St. Charles County Recycle Works location (Wentzville).', 'Western St. Charles County Recycle Works location (Wentzville).', 'Prefer over Central for Wentzville/Foristell recycling splits when open.',
  'mixed', 25, null, 25, false,
  'Same county Recycle Works fee schedule as Central — confirm current sheet.', null,
  null, null, null, null,
  false, '{"cash","check","credit_card"}'::text[],
  'verified', '[{"label":"Recycle Works fee sheet listing West address","url":"https://mo-stcharlescounty.civicplus.com/Archive/ViewFile/Item/4998","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, '2026-07-10'::timestamptz, 'nominatim_openstreetmap',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-champ-landfill', 'morris-hauling', 'Champ Landfill', '2280 Maryland Heights Expressway', 'Maryland Heights', 'MO', '63043', 'St. Louis',
  38.7435969, -90.4675795, '(314) 291-0887', 'https://www.champlandfill.com/',
  'sanitary_landfill', 'both', true, false, 'none',
  '{"mon":"7:00 AM – 4:00 PM","tue":"7:00 AM – 4:00 PM","wed":"7:00 AM – 4:00 PM","thu":"7:00 AM – 4:00 PM","fri":"7:00 AM – 4:00 PM","sat":"7:00 AM – 11:00 AM","sun":"Closed"}'::jsonb, '{"New Year''s Day","Memorial Day","Independence Day","Labor Day","Thanksgiving Day","Christmas Day"}'::text[], '{"mixed_junk","household_trash","furniture","mattresses","construction_demolition","concrete","asphalt","clean_fill","commercial_waste"}'::text[], '{"Major appliances","Bulk liquids","Explosives","Propane containers","Radioactive materials","Regulated infectious / hazardous / PCB waste","Septic tank pumpings","Whole tires","Waste oil","Yard waste (keep separate)"}'::text[],
  'Loads must be tarped. Hard hats and safety vests required (available at scale house). Credit/debit card customers must arrive by 3:30 PM weekdays. One-ton minimum on published public gate rate.', 'DNR-listed sanitary landfill. Open to general public and haulers from any location per facility FAQ. Does not offer recycling drop-off.', 'DNR-listed sanitary landfill. Open to general public and haulers from any location per facility FAQ. Does not offer recycling drop-off.', 'Strong St. Louis County option for MSW/C&D. Published public gate rate is high — always confirm commercial/account rate before using in estimates.',
  'weight', null, 324.61, 324.61, false,
  'Public gate rate $324.61/ton effective Feb 6, 2023 per Champ FAQ (one-ton minimum). Re-verify before quoting — rate may have changed.', 'Commercial/account rates not published on FAQ — call (314) 291-0887.',
  null, null, null, null,
  true, '{"american_express","discover","mastercard","visa"}'::text[],
  'verified', '[{"label":"Champ Landfill FAQ","url":"https://www.champlandfill.com/faq/","retrievedAt":"2026-07-10"},{"label":"Champ Landfill contact","url":"https://www.champlandfill.com/contact/","retrievedAt":"2026-07-10"},{"label":"Missouri DNR operating sanitary landfills","url":"https://dnr.mo.gov/waste-recycling/sites-regulated-facilities/operating-solid-waste-landfills","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, '2026-07-10'::timestamptz, 'nominatim_openstreetmap',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-bridgeton-transfer', 'morris-hauling', 'Bridgeton Transfer Station LLC', '13570 St. Charles Rock Road', 'Bridgeton', 'MO', '63044', 'St. Louis',
  38.7706226, -90.4437911, null, null,
  'transfer_station', 'both', true, false, 'unknown',
  '{"mon":"7:00 AM – 5:00 PM","tue":"7:00 AM – 5:00 PM","wed":"7:00 AM – 5:00 PM","thu":"7:00 AM – 5:00 PM","fri":"7:00 AM – 5:00 PM","sat":"7:00 AM – 12:00 PM","sun":"Closed"}'::jsonb, '{}'::text[], '{"mixed_junk","household_trash","construction_demolition","commercial_waste"}'::text[], '{}'::text[],
  'Call facility before first commercial load to confirm acceptance, PPE, and payment rules.', 'DNR-listed Bridgeton Transfer Station LLC. Hours from secondary directories — confirm by phone before routing.', 'DNR-listed Bridgeton Transfer Station LLC. Hours from secondary directories — confirm by phone before routing.', 'Needs_call for phone, tip rates, and commercial account setup.',
  'weight', null, null, null, true,
  null, null,
  null, null, null, null,
  null, '{}'::text[],
  'needs_call', '[{"label":"Missouri DNR operating transfer stations","url":"https://dnr.mo.gov/waste-recycling/sites-regulated-facilities/operating-solid-waste-processing","retrievedAt":"2026-07-10"},{"label":"Secondary hours listing (confirm by phone)","url":"https://nearestlandfill.com/org/bridgeton-transfer-station/","retrievedAt":"2026-07-10","notes":"Hours not confirmed on an operator-owned page during research."}]'::jsonb, '2026-07-10'::timestamptz, null, 'nominatim_openstreetmap',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-valley-park-transfer', 'morris-hauling', 'Valley Park Transfer Station (FW Disposal LLC)', '200 South Elam Avenue', 'Valley Park', 'MO', '63088', 'St. Louis',
  38.5412829, -90.499242, null, 'https://www.wasteconnections.com/valley-park-transfer-station',
  'transfer_station', 'both', true, false, 'unknown',
  '{}'::jsonb, '{}'::text[], '{"mixed_junk","household_trash","construction_demolition","commercial_waste"}'::text[], '{}'::text[],
  'Confirm hours, materials, and commercial rates with Waste Connections before routing.', 'DNR lists FW Disposal LLC Transfer Station (Valley Park). Waste Connections location page confirms 200 South Elam address; hours/rates not clearly published on page content retrieved.', 'DNR lists FW Disposal LLC Transfer Station (Valley Park). Waste Connections location page confirms 200 South Elam address; hours/rates not clearly published on page content retrieved.', 'needs_call before first use — do not assume hours from unrelated WC pages.',
  'weight', null, null, null, true,
  null, null,
  null, null, null, null,
  null, '{}'::text[],
  'needs_call', '[{"label":"Missouri DNR operating transfer stations","url":"https://dnr.mo.gov/waste-recycling/sites-regulated-facilities/operating-solid-waste-processing","retrievedAt":"2026-07-10"},{"label":"Waste Connections Valley Park Transfer Station","url":"https://www.wasteconnections.com/valley-park-transfer-station","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'nominatim_openstreetmap',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-wm-kimmswick-transfer', 'morris-hauling', 'Kimmswick Transfer Station (Waste Management)', '311 Mill Street', 'Kimmswick', 'MO', '63053', 'Jefferson',
  38.3647809, -90.3653308, '(636) 282-4652', 'https://www.wmsolutions.com/locations/details/id/594',
  'transfer_station', 'both', true, false, 'none',
  '{"mon":"6:00 AM – 3:00 PM","tue":"6:00 AM – 3:00 PM","wed":"6:00 AM – 3:00 PM","thu":"6:00 AM – 3:00 PM","fri":"6:00 AM – 3:00 PM","sat":"Closed","sun":"Closed"}'::jsonb, '{"New Year''s Day","Memorial Day","Independence Day","Labor Day","Thanksgiving Day","Christmas Day"}'::text[], '{"mixed_junk","household_trash","construction_demolition","commercial_waste"}'::text[], '{"Hazardous waste"}'::text[],
  'Hard hat and high-visibility vest required. Hand-unload customers must enter by 2:30 PM.', 'DNR-listed Kimmswick Transfer Station. Jefferson County hauler list publishes phone (636) 282-4652.', 'DNR-listed Kimmswick Transfer Station. Jefferson County hauler list publishes phone (636) 282-4652.', 'Good Jefferson County MSW/C&D option. Tip rates not on WM page — call for commercial quote.',
  'weight', null, null, null, true,
  null, null,
  null, null, null, null,
  true, '{"credit_card","debit_card","credit_account"}'::text[],
  'partial', '[{"label":"WMSolutions Kimmswick Transfer Station","url":"https://www.wmsolutions.com/locations/details/id/594","retrievedAt":"2026-07-10"},{"label":"Missouri DNR operating transfer stations","url":"https://dnr.mo.gov/waste-recycling/sites-regulated-facilities/operating-solid-waste-processing","retrievedAt":"2026-07-10"},{"label":"Jefferson County residential waste haulers / transfer list","url":"https://www.jeffcomo.org/DocumentCenter/View/12866","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'nominatim_openstreetmap',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-wm-desoto-transfer', 'morris-hauling', 'DeSoto Transfer Station (Waste Management)', '3902 Athena School Road', 'De Soto', 'MO', '63020', 'Jefferson',
  38.11720027, -90.47582692, '(636) 586-7734', 'https://www.wmsolutions.com/locations/details/id/648',
  'transfer_station', 'both', true, false, 'none',
  '{"mon":"7:00 AM – 3:00 PM","tue":"7:00 AM – 3:00 PM","wed":"7:00 AM – 3:00 PM","thu":"7:00 AM – 3:00 PM","fri":"7:00 AM – 3:00 PM","sat":"Closed","sun":"Closed"}'::jsonb, '{"New Year''s Day","Memorial Day","Independence Day","Labor Day","Thanksgiving Day","Christmas Day"}'::text[], '{"mixed_junk","household_trash","construction_demolition","commercial_waste"}'::text[], '{"Hazardous waste"}'::text[],
  'Confirm material acceptance and commercial account requirements with facility before first load.', 'DNR-listed Jefferson County Transfer Station (DeSoto). Jefferson County list phone (636) 586-7734.', 'DNR-listed Jefferson County Transfer Station (DeSoto). Jefferson County list phone (636) 586-7734.', 'Southern Jefferson County tip. Rates not published — call ahead.',
  'weight', null, null, null, true,
  null, null,
  null, null, null, null,
  true, '{"cash","check","credit_account"}'::text[],
  'partial', '[{"label":"WMSolutions DeSoto Transfer Station","url":"https://www.wmsolutions.com/locations/details/id/648","retrievedAt":"2026-07-10"},{"label":"Missouri DNR operating transfer stations","url":"https://dnr.mo.gov/waste-recycling/sites-regulated-facilities/operating-solid-waste-processing","retrievedAt":"2026-07-10"},{"label":"Jefferson County residential waste haulers / transfer list","url":"https://www.jeffcomo.org/DocumentCenter/View/12866","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'us_census_geocoder',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-struckhoff-landfill', 'morris-hauling', 'City of Washington (Struckhoff) Landfill', '925 Struckhoff Lane', 'Washington', 'MO', '63090', 'Franklin',
  38.58485039, -91.06301975, '(636) 390-1039', 'https://washmo.gov/',
  'sanitary_landfill', 'both', true, false, 'unknown',
  '{}'::jsonb, '{}'::text[], '{"mixed_junk","household_trash","construction_demolition","commercial_waste","furniture"}'::text[], '{}'::text[],
  'Call (636) 390-1039 for current hours, commercial acceptance, prohibited items, and tip fees before routing.', 'DNR-listed City of Washington (Struckhoff) Landfill. City website landfill page returned 403 during research; phone and address confirmed via multiple directories.', 'DNR-listed City of Washington (Struckhoff) Landfill. City website landfill page returned 403 during research; phone and address confirmed via multiple directories.', 'Replaces incorrect prior seed ''Franklin County Sanitary Landfill'' at East Main Street. Confirm hours/rates by phone — do not invent.',
  'weight', null, null, null, true,
  null, null,
  null, null, null, null,
  true, '{}'::text[],
  'needs_call', '[{"label":"Missouri DNR operating sanitary landfills","url":"https://dnr.mo.gov/waste-recycling/sites-regulated-facilities/operating-solid-waste-landfills","retrievedAt":"2026-07-10"},{"label":"Struckhoff Sanitary Landfill listing","url":"https://locator.wastebits.com/location/struckhoff-sanitary-landfill","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'us_census_geocoder',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-timber-ridge-landfill', 'morris-hauling', 'Timber Ridge Landfill', '12581 State Highway H', 'Richwoods', 'MO', '63071', 'Washington',
  38.16767148, -90.76524405, '(636) 321-2100', 'https://www.wasteconnections.com/timber-ridge-landfill',
  'sanitary_landfill', 'both', true, false, 'none',
  '{}'::jsonb, '{}'::text[], '{"mixed_junk","household_trash","construction_demolition","commercial_waste"}'::text[], '{}'::text[],
  'Confirm hours and commercial rates with Waste Connections (636) 321-2100 before routing.', 'DNR-listed Timber Ridge Landfill (Richwoods, Washington County). Waste Connections operated.', 'DNR-listed Timber Ridge Landfill (Richwoods, Washington County). Waste Connections operated.', 'Expansion-south option. WC page did not clearly expose local hours/rates in retrieved content.',
  'weight', null, null, null, true,
  null, null,
  null, null, null, null,
  true, '{}'::text[],
  'needs_call', '[{"label":"Missouri DNR operating sanitary landfills","url":"https://dnr.mo.gov/waste-recycling/sites-regulated-facilities/operating-solid-waste-landfills","retrievedAt":"2026-07-10"},{"label":"Waste Connections Timber Ridge Landfill","url":"https://www.wasteconnections.com/timber-ridge-landfill","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'us_census_geocoder',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-prairie-valley-landfill', 'morris-hauling', 'Prairie Valley Landfill', '3975 Highway 19', 'Cuba', 'MO', '65453', 'Crawford',
  38.12051259, -91.42906681, '(573) 885-7596', null,
  'sanitary_landfill', 'both', true, false, 'unknown',
  '{"mon":"6:00 AM – 2:30 PM","tue":"6:00 AM – 2:30 PM","wed":"6:00 AM – 2:30 PM","thu":"6:00 AM – 2:30 PM","fri":"6:00 AM – 2:30 PM","sat":"Closed","sun":"Closed"}'::jsonb, '{}'::text[], '{"mixed_junk","household_trash","construction_demolition","commercial_waste"}'::text[], '{}'::text[],
  'Confirm hours, materials, and tip fees by phone before first commercial load.', 'DNR-listed Prairie Valley Landfill (Cuba, Crawford County). Hours from secondary directories — confirm by phone.', 'DNR-listed Prairie Valley Landfill (Cuba, Crawford County). Hours from secondary directories — confirm by phone.', 'Far-south expansion option for Crawford/Gasconade corridor.',
  'weight', null, null, null, true,
  null, null,
  null, null, null, null,
  true, '{}'::text[],
  'needs_call', '[{"label":"Missouri DNR operating sanitary landfills","url":"https://dnr.mo.gov/waste-recycling/sites-regulated-facilities/operating-solid-waste-landfills","retrievedAt":"2026-07-10"},{"label":"Secondary hours listing (confirm by phone)","url":"https://nearestlandfill.com/org/prairie-valley-sanitary-landfill/","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'us_census_geocoder',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-st-francois-transfer', 'morris-hauling', 'St. Francois County Solid Waste Transfer Station', '200 Landfill Road', 'Park Hills', 'MO', '63601', 'St. Francois',
  37.87267676, -90.5474949, '(573) 431-4768', null,
  'transfer_station', 'both', true, false, 'unknown',
  '{}'::jsonb, '{}'::text[], '{"mixed_junk","household_trash","construction_demolition","commercial_waste"}'::text[], '{}'::text[],
  'Call (573) 431-4768 for hours, commercial acceptance, and rates before routing.', 'DNR-listed St. Francois County Solid Waste Transfer Station (Park Hills).', 'DNR-listed St. Francois County Solid Waste Transfer Station (Park Hills).', 'Address geocoded via Census for 200 Landfill Rd, Park Hills — confirm gate address on first visit.',
  'weight', null, null, null, true,
  null, null,
  null, null, null, null,
  null, '{}'::text[],
  'needs_call', '[{"label":"Missouri DNR operating transfer stations","url":"https://dnr.mo.gov/waste-recycling/sites-regulated-facilities/operating-solid-waste-processing","retrievedAt":"2026-07-10"},{"label":"St. Francois County Transfer Station listing","url":"https://locator.wastebits.com/location/st-francois-county-transfer-station","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'us_census_geocoder',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-rock-hill-demolition', 'morris-hauling', 'Rock Hill Quarries Co. Demolition Landfill', '1233 North Rock Hill Road', 'St. Louis', 'MO', '63124', 'St. Louis',
  38.61447595, -90.36456597, '(314) 968-2336', null,
  'demolition_landfill', 'commercial', true, false, 'none',
  '{}'::jsonb, '{}'::text[], '{"construction_demolition","concrete","brick","wood","clean_fill","dirt","rock"}'::text[], '{"Municipal solid waste / household trash","Hazardous waste"}'::text[],
  'Demolition landfill — C&D / inert materials only per DNR demolition landfill category. Call to confirm accepted C&D list and rates.', 'DNR-listed operating demolition landfill (St. Louis County).', 'DNR-listed operating demolition landfill (St. Louis County).', 'Use for clean C&D splits when cheaper than MSW tip — never send mixed household junk.',
  'weight', null, null, null, true,
  null, null,
  null, null, null, null,
  null, '{}'::text[],
  'needs_call', '[{"label":"Missouri DNR operating demolition landfills","url":"https://dnr.mo.gov/waste-recycling/sites-regulated-facilities/operating-solid-waste-landfills","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'us_census_geocoder',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-east-central-recycling', 'morris-hauling', 'East Central Missouri Recycling Center', '24448 South Highway 47', 'Warrenton', 'MO', '63383', 'Warren',
  38.75833001, -91.14396049, '(636) 456-3473', 'http://boonslick.org/recycling-center/',
  'recycling_center', 'public', false, false, 'unknown',
  '{"mon":"Closed","tue":"Closed","wed":"8:00 AM – 5:00 PM","thu":"8:00 AM – 5:00 PM","fri":"8:00 AM – 5:00 PM","sat":"8:00 AM – 12:00 PM","sun":"Closed"}'::jsonb, '{}'::text[], '{"recycling","electronics","cardboard","scrap_metal","appliances","tires","batteries"}'::text[], '{}'::text[],
  'Serves Franklin, Lincoln, Montgomery, and Warren counties per RecycleSearch profile. Confirm commercial drop-off rules and item fees by phone.', 'Primary Warren County recycling drop-off referenced by City of Warrenton.', 'Primary Warren County recycling drop-off referenced by City of Warrenton.', 'Use for separated recycling/e-waste/metal from Warren-area jobs. Hours from secondary directories — confirm before routing. Not an MSW landfill.',
  'per_item', null, null, null, true,
  'Some items (tires, monitors, appliances) may have fees — call (636) 456-3473.', null,
  null, null, null, null,
  false, '{}'::text[],
  'partial', '[{"label":"City of Warrenton helpful numbers / recycling center","url":"https://www.warrenton-mo.org/helpful-numbers/","retrievedAt":"2026-07-10"},{"label":"East Central Missouri Recycling Center profile","url":"https://recyclesearch.com/profile/29553","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'us_census_geocoder',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-milam-landfill', 'morris-hauling', 'Milam Recycling & Disposal Facility', '601 Madison Road', 'East St. Louis', 'IL', '62201', 'St. Clair',
  38.6482292, -90.13004384, '(618) 271-6788', 'https://www.wmsolutions.com/locations/details/id/31',
  'sanitary_landfill', 'both', true, false, 'none',
  '{"mon":"6:00 AM – 3:00 PM","tue":"6:00 AM – 3:00 PM","wed":"6:00 AM – 3:00 PM","thu":"6:00 AM – 3:00 PM","fri":"6:00 AM – 3:00 PM","sat":"Closed","sun":"Closed"}'::jsonb, '{"New Year''s Day","Memorial Day","Independence Day","Labor Day","Thanksgiving Day","Christmas Day"}'::text[], '{"mixed_junk","household_trash","construction_demolition","clean_fill","dirt","commercial_waste"}'::text[], '{"Hazardous waste","Tires","White goods / appliances","Household hazardous waste","Liquid paint"}'::text[],
  'Credit-card and hand-unload customers must arrive at least 60 minutes before closing (no entry after 3:00 PM Mon–Fri per WM page note). Trucks up to 48 ft; site has truck tipper.', 'St. Clair County Health lists Milam as an active landfill with public drop-off. WMSolutions hours used as operator source (county PDF hours differed historically).', 'St. Clair County Health lists Milam as an active landfill with public drop-off. WMSolutions hours used as operator source (county PDF hours differed historically).', 'Primary Metro East MSW option. Tip rates not published — call for commercial quote.',
  'weight', null, null, null, true,
  'Fees vary — St. Clair County advises contacting landfill before arrival.', null,
  null, null, 'Trucks may be up to 48 feet in length.', null,
  true, '{"credit_card","debit_card","credit_account"}'::text[],
  'partial', '[{"label":"WMSolutions Milam Landfill","url":"https://www.wmsolutions.com/locations/details/id/31","retrievedAt":"2026-07-10"},{"label":"St. Clair County landfill information PDF","url":"https://www.co.st-clair.il.us/WebDocuments/Departments/Health/pollution/St.%20Clair%20County%20landfill%20information.pdf","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'us_census_geocoder',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-cottonwood-hills', 'morris-hauling', 'Cottonwood Hills Recycling & Disposal Facility', '10400 Hillstown Road', 'Marissa', 'IL', '62257', 'St. Clair',
  38.2643664, -89.779378, '(618) 295-2809', 'https://www.wmsolutions.com/locations/details/id/62',
  'sanitary_landfill', 'both', true, false, 'none',
  '{"mon":"5:30 AM – 3:00 PM","tue":"5:30 AM – 3:00 PM","wed":"5:30 AM – 3:00 PM","thu":"5:30 AM – 3:00 PM","fri":"5:30 AM – 3:00 PM","sat":"Closed","sun":"Closed"}'::jsonb, '{"New Year''s Day","Memorial Day","Independence Day","Labor Day","Thanksgiving Day","Christmas Day"}'::text[], '{"mixed_junk","household_trash","construction_demolition","commercial_waste"}'::text[], '{"Hazardous waste","Tires","White goods / appliances","Household hazardous waste","Liquid paint"}'::text[],
  'Hand-unload or credit-card customers cannot enter after 2:00 PM. Trucks up to 53 ft; site has truck tipper.', 'St. Clair County Health lists Cottonwood Hills as an active landfill. WMSolutions hours used as operator source.', 'St. Clair County Health lists Cottonwood Hills as an active landfill. WMSolutions hours used as operator source.', 'Farther south St. Clair option — usually secondary to Milam for Morris Metro East jobs.',
  'weight', null, null, null, true,
  null, null,
  null, null, 'Trucks may be up to 53 feet in length.', null,
  true, '{"credit_card","debit_card"}'::text[],
  'partial', '[{"label":"WMSolutions Cottonwood Hills","url":"https://www.wmsolutions.com/locations/details/id/62","retrievedAt":"2026-07-10"},{"label":"St. Clair County landfill information PDF","url":"https://www.co.st-clair.il.us/WebDocuments/Departments/Health/pollution/St.%20Clair%20County%20landfill%20information.pdf","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'nominatim_openstreetmap',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-roxana-landfill', 'morris-hauling', 'Roxana Landfill', '4601 Cahokia Creek Road', 'Edwardsville', 'IL', '62025', 'Madison',
  38.82699905, -90.01248646, '(618) 656-6883', null,
  'sanitary_landfill', 'both', true, false, 'none',
  '{"mon":"7:00 AM – 4:00 PM","tue":"7:00 AM – 4:00 PM","wed":"7:00 AM – 4:00 PM","thu":"7:00 AM – 4:00 PM","fri":"7:00 AM – 4:00 PM","sat":"Closed","sun":"Closed"}'::jsonb, '{}'::text[], '{"mixed_junk","household_trash","construction_demolition","commercial_waste"}'::text[], '{"Hazardous waste","Tires","White goods / appliances","Household hazardous waste","Liquid paint"}'::text[],
  'Confirm current hours, commercial rates, and prohibited items by phone before routing.', 'Madison County MSW landfill (Roxana Landfill, Inc.). Address confirmed via IEPA NPDES public notice. Hours from secondary directories — confirm by phone.', 'Madison County MSW landfill (Roxana Landfill, Inc.). Address confirmed via IEPA NPDES public notice. Hours from secondary directories — confirm by phone.', 'Primary Madison County tip. Phone numbers vary across directories — try (618) 656-6883 / (618) 656-6912.',
  'weight', null, null, null, true,
  null, null,
  null, null, null, null,
  true, '{}'::text[],
  'needs_call', '[{"label":"IEPA NPDES public notice — Roxana Landfill","url":"https://webapps.illinois.gov/EPA/WebSiteApi/api/PublicNotices/GetDocument/35553","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'us_census_geocoder',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();

insert into public.dump_sites (
  id, company_id, name, address, city, state, zip, county,
  latitude, longitude, phone, website,
  facility_type, access_type, commercial_accepted, appointment_required, residency_restriction,
  hours_json, holiday_closures, accepted_materials, rejected_materials,
  special_requirements, operational_notes, notes, internal_notes,
  fee_type, base_fee, per_ton_fee, minimum_fee, pricing_unknown,
  public_pricing_notes, commercial_pricing_notes,
  weight_limit_tons, trailer_restrictions, truck_restrictions, max_load_size,
  scale_available, payment_methods,
  verification_status, verification_sources, verified_at, pricing_verified_at, geocode_source,
  status, is_closed, updated_at
) values (
  'fac-monroe-county-recycling', 'morris-hauling', 'Monroe County Recycling Center / Dump Site', '901 Illinois Avenue', 'Waterloo', 'IL', '62298', 'Monroe',
  38.338519, -90.161808, '(618) 939-3871', 'https://monroecountyhealth.org/monroe-county-recycling-center/',
  'recycling_center', 'public', false, false, 'county_residents',
  '{"mon":"8:00 AM – 4:00 PM","tue":"8:00 AM – 4:00 PM","wed":"8:00 AM – 4:00 PM","thu":"8:00 AM – 4:00 PM","fri":"8:00 AM – 4:00 PM","sat":"8:00 AM – 12:00 PM","sun":"Closed"}'::jsonb, '{"Holidays"}'::text[], '{"recycling","cardboard","scrap_metal","electronics","appliances","mixed_junk","furniture","mattresses","construction_demolition"}'::text[], '{"Oil","Chemicals","Tires","Paint","Concrete / stone","Yard debris","Styrofoam","Plastic bags"}'::text[],
  'Located behind Annex building. No large loads after 3:45 PM weekdays / 11:45 AM Saturday. Sort recyclables before arrival. Keep children/pets in vehicles. Confirm commercial hauler acceptance before routing Morris loads.', 'Monroe County Health Department facility. Free recycling for listed commodities; disposal fees for trash/C&D/furniture/etc.; metal/electronics/appliances free to dump per county page.', 'Monroe County Health Department facility. Free recycling for listed commodities; disposal fees for trash/C&D/furniture/etc.; metal/electronics/appliances free to dump per county page.', 'Likely resident-oriented. Do not assume commercial acceptance — call Brian Eckert 618.939.3871 ext. 212 or site coordinators before first use.',
  'mixed', null, null, null, true,
  'Fee schedule for charged items not fully published as dollar amounts — call for current prices.', null,
  null, null, null, null,
  false, '{}'::text[],
  'partial', '[{"label":"Monroe County Health Department Recycling Center","url":"https://monroecountyhealth.org/monroe-county-recycling-center/","retrievedAt":"2026-07-10"}]'::jsonb, '2026-07-10'::timestamptz, null, 'nominatim_openstreetmap',
  'active', false, now()
)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  county = excluded.county,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  phone = excluded.phone,
  website = excluded.website,
  facility_type = excluded.facility_type,
  access_type = excluded.access_type,
  commercial_accepted = excluded.commercial_accepted,
  appointment_required = excluded.appointment_required,
  residency_restriction = excluded.residency_restriction,
  hours_json = excluded.hours_json,
  holiday_closures = excluded.holiday_closures,
  accepted_materials = excluded.accepted_materials,
  rejected_materials = excluded.rejected_materials,
  special_requirements = excluded.special_requirements,
  operational_notes = excluded.operational_notes,
  notes = excluded.notes,
  internal_notes = excluded.internal_notes,
  fee_type = excluded.fee_type,
  base_fee = excluded.base_fee,
  per_ton_fee = excluded.per_ton_fee,
  minimum_fee = excluded.minimum_fee,
  pricing_unknown = excluded.pricing_unknown,
  public_pricing_notes = excluded.public_pricing_notes,
  commercial_pricing_notes = excluded.commercial_pricing_notes,
  weight_limit_tons = excluded.weight_limit_tons,
  trailer_restrictions = excluded.trailer_restrictions,
  truck_restrictions = excluded.truck_restrictions,
  max_load_size = excluded.max_load_size,
  scale_available = excluded.scale_available,
  payment_methods = excluded.payment_methods,
  verification_status = excluded.verification_status,
  verification_sources = excluded.verification_sources,
  verified_at = excluded.verified_at,
  pricing_verified_at = excluded.pricing_verified_at,
  geocode_source = excluded.geocode_source,
  status = excluded.status,
  updated_at = now();
