import {
  Armchair,
  Battery,
  BrickWall,
  Droplets,
  Flame,
  Hammer,
  Leaf,
  Package,
  Recycle,
  Refrigerator,
  Trash2,
  TreeDeciduous,
  Truck,
  Tv,
  Warehouse,
  Wind,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { MaterialCategory } from "@/lib/disposal/material-categories";

const ICON_MAP: Partial<Record<MaterialCategory, LucideIcon>> = {
  household_trash: Trash2,
  mixed_junk: Package,
  furniture: Armchair,
  appliances: Refrigerator,
  freon_appliances: Wind,
  construction_demolition: Hammer,
  concrete: BrickWall,
  brick: BrickWall,
  drywall: BrickWall,
  wood: TreeDeciduous,
  roofing: Warehouse,
  scrap_metal: Wrench,
  copper: Wrench,
  steel: Wrench,
  aluminum: Wrench,
  yard_waste: Leaf,
  brush: TreeDeciduous,
  leaves: Leaf,
  tree_limbs: TreeDeciduous,
  logs: TreeDeciduous,
  stumps: TreeDeciduous,
  mattresses: Armchair,
  electronics: Tv,
  tires: Truck,
  paint: Droplets,
  oil: Droplets,
  batteries: Battery,
  propane: Flame,
  hazardous_waste: Flame,
  freon: Wind,
  clean_fill: BrickWall,
  mixed_cd: Hammer,
  recycling: Recycle,
  cardboard: Package,
  commercial_waste: Truck,
};

export function getMaterialIcon(category: MaterialCategory): LucideIcon {
  return ICON_MAP[category] ?? Package;
}
